# Generated by Django 4.0.5 on 2022-06-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
